---
title: "IntradayMomentum"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Intraday Momentum - SPY

```{r echo=FALSE}
#Clear Workspace
rm(list = ls())
```

```{r echo=FALSE, warning=FALSE, message = FALSE}
#Source files
source('./libraries.R')
source('./functions.R')
```

```{r echo = FALSE}
#Load Data
data <- loadData(ticker = 'SPY')
```

## Preliminary data analysis
```{r, echo = FALSE, warning=FALSE}
histogram(data$R1, 'First 30-Minute Returns', 'R1')
describe(data$R1)
histogram(data$R13, 'Last 30-Minute Returns', 'R3')
describe(data$R13)
#histogram(data$V1, 'First 30-Minute Volatility', 'Vol')
#describe(data$V1)
#histogram(data$V13, 'Last 30-Minute Volatility', 'Vol')
#describe(data$V13)
histogram(data$Vol, 'Daily Log Volatility', 'Vol')
describe(data$Vol)
histogram(data$Size, 'Trade Size', 'Size')
describe(data$Size)
```

## Regression
```{r echo = FALSE}
#Combined Columns for 2-variable interaction and higher order terms
#Note: We need to manually create these variables - simply writing X1*X2 in formula won't work
#data[, c('R1_V1', 'R5_V5') := list(R1 * V1, R5 * V5)]

#TODO: Check Xi^2 effects

#R13 = B0 + B1*R1 + B2*R2 + ... + B12*R12
formula <- paste("R13 ~", paste(setdiff(retCols, 'R13'), collapse = " + "))
model <- lm(formula, data = data)
summary(model)

## Newey West Robust T-statistic
#Note: This will not effect R^2 or coefficients - provides adjusted t-statistic
print('Newey West Robust T-statistic')
coeftest(model, vcov = vcovHC(model))
```

## Strategies
```{r}
#Long/Short Strategy
#Predict value
data[, Strat1Signal := predict(model)]
data[, Strat1Ret := ifelse(Strat1Signal > 0, R13, -R13)]
data[, Strat1CumRet := cumprod(1 + Strat1Ret)]

#Random Strategy
data[, RandomSignal := rbinom(.N, 1, .5)]
data[, RandomRet := ifelse(Strat1Signal == 1, R13, -R13)]
data[, RandomCumRet := cumprod(1 + RandomRet)]

#SPY Hold Strategy
data[, SPYRet := Close / shift(Close) - 1]
data[is.na(SPYRet), SPYRet := 0]
data[, SPYCumRet := cumprod(1 + SPYRet)]
```

## Plot Strategies
```{r echo = FALSE}
#Plot strategies
plot <- ggplot() +
  geom_line(data = data, aes(x = Date, y = SPYCumRet, colour = 'SPY Long')) + 
  geom_line(data = data, aes(x = Date, y = Strat1CumRet, colour = 'Long/Short Strategy')) + 
  geom_line(data = data, aes(x = Date, y = RandomCumRet, colour = 'Random Strategy')) + 
  xlab('Dates') + ylab('Return') + ggtitle('Strategy Return')
plot(plot)
```

## Histogram of Strategy returns
```{r echo = FALSE, warning=FALSE}
histogram(data$Strat1Ret, 'Long/Short Strategy Daily Returns', 'Strat1Ret')
histogram(data$Strat1Ret - data$SPYRet, 'Excess Daily Returns', 'Excess Returns')
```

## Omit observations with daily volatility oustide 2 and 3 standard devations
```{r echo=FALSE}
data[, c('Strat1Ret_Vol2', 'Strat1Ret_Vol3') := list(Strat1Ret, Strat1Ret)]
data[!(Vol %between% c(mean(Vol) - 2*sd(Vol), mean(Vol) + 2*sd(Vol))), Strat1Ret_Vol2 := 0]
data[!(Vol %between% c(mean(Vol) - 3*sd(Vol), mean(Vol) + 3*sd(Vol))), Strat1Ret_Vol3 := 0]

data[, Strat1_Vol2CumRet := cumprod(1 + Strat1Ret_Vol2)]
data[, Strat1_Vol3CumRet := cumprod(1 + Strat1Ret_Vol3)]

#Plot Long/Hold std modified strategy
plot <- ggplot() +
  geom_line(data = data, aes(x = Date, y = SPYCumRet, colour = 'SPY Long')) + 
  geom_line(data = data, aes(x = Date, y = Strat1CumRet, colour = 'Long/Short Strategy')) + 
  geom_line(data = data, aes(x = Date, y = Strat1_Vol2CumRet, colour = 'Long/Short Strategy +/- 2 Std. Dev. Volatility')) + 
  geom_line(data = data, aes(x = Date, y = Strat1_Vol3CumRet, colour = 'Long/Short Strategy +/- 3 Std. Dev. Volatility')) + 
  xlab('Dates') + ylab('Return') + ggtitle('Strategy Return')
plot(plot)
```

## Histograms of strategies modified by volatility
```{r, echo = FALSE, warning=FALSE}
histogram(data$Strat1Ret - data$SPYRet, 'Long/Short Strategy Daily Returns', 'Returns')
describe(data$Strat1Ret - data$SPYRet)
histogram(data$Strat1Ret_Vol2 - data$SPYRet, 'Long/Short Strategy (+/- 2 Std. Dev. Volatility) Excess Daily Returns', 'Returns')
describe(data$Strat1Ret_Vol2 - data$SPYRet)
histogram(data$Strat1Ret_Vol3 - data$SPYRet, 'Long/Short Strategy (+/- 3 Std. Dev. Volatility) Excess Daily Returns', 'Returns')
describe(data$Strat1Ret_Vol3 - data$SPYRet)
```


```{r, echo=FALSE, warning=FALSE}
#Rolling Regression Data
#250 trading days a year * 3 years
lookback <- 250*3

rollingRegression <- data.frame(Date = as.character(), CoeffR1 = as.numeric(), CoeffR5 = as.numeric(), 
                                PValR1 = as.numeric(), PValR5 = as.numeric(),
                                AdjRSquared = as.numeric(), ResidualStdErr = as.numeric(), 
                                Lookback = as.logical(), stringsAsFactors = FALSE)

#Apply rolling regression
#date <- as.Date('2014-01-01')
for(date in data[Date >= '2004-01-01', Date]) {
  date <- as.Date(date)
  temp <- rollRegressFunc(data[Date <= date & Date > date - lookback], isLookback = TRUE)
  rollingRegression <- rbind(rollingRegression, temp)
  temp <- rollRegressFunc(data[Date <= date], isLookback = FALSE)
  rollingRegression <- rbind(rollingRegression, temp)
}

rollingRegression[, Date := as.Date(Date)]
```


## Rolling Regression
### Lookback
```{r echo = FALSE}
#Coeffs
plot <- ggplot() +
  geom_line(data = rollingRegression[Lookback == TRUE], aes(x = Date, y = CoeffR1, colour = 'R1')) + 
  geom_line(data = rollingRegression[Lookback == TRUE], aes(x = Date, y = CoeffR5, colour = 'R5')) + 
  xlab('Dates') + ylab('Coefficient') + ggtitle('Regression Coefficients')
plot(plot)

#T-Statistics
plot <- ggplot() +
  geom_line(data = rollingRegression[Lookback == TRUE], aes(x = Date, y = PValR1, colour = 'R1')) + 
  geom_line(data = rollingRegression[Lookback == TRUE], aes(x = Date, y = PValR5, colour = 'R5')) + 
  xlab('Dates') + ylab('P-Value') + ggtitle('Newey West Robust T-statistics for P-Value')
plot(plot)

#Adjusted R-Squared
plot <- ggplot() +
  geom_line(data = rollingRegression[Lookback == TRUE], aes(x = Date, y = AdjRSquared, colour = 'R^2')) + 
  xlab('Dates') + ylab('R^2') + ggtitle('Adjusted R-Squared')
plot(plot)

#Residual Standard Error
plot <- ggplot() +
  geom_line(data = rollingRegression[Lookback == TRUE], aes(x = Date, y = ResidualStdErr, colour = 'Error')) + 
  xlab('Dates') + ylab('Error') + ggtitle('Standard Error of Residuals')
plot(plot)
```

### Complete History
```{r echo = FALSE}
#Coeffs
plot <- ggplot() +
  geom_line(data = rollingRegression[Lookback == FALSE], aes(x = Date, y = CoeffR1, colour = 'R1')) + 
  geom_line(data = rollingRegression[Lookback == FALSE], aes(x = Date, y = CoeffR5, colour = 'R5')) + 
  xlab('Dates') + ylab('Coefficient') + ggtitle('Regression Coefficients')
plot(plot)

#T-Statistics
plot <- ggplot() +
  geom_line(data = rollingRegression[Lookback == FALSE], aes(x = Date, y = PValR1, colour = 'R1')) + 
  geom_line(data = rollingRegression[Lookback == FALSE], aes(x = Date, y = PValR5, colour = 'R5')) + 
  xlab('Dates') + ylab('P-Value') + ggtitle('Newey West Robust T-statistics for P-Value')
plot(plot)

#Adjusted R-Squared
plot <- ggplot() +
  geom_line(data = rollingRegression[Lookback == FALSE], aes(x = Date, y = AdjRSquared, colour = 'R^2')) + 
  xlab('Dates') + ylab('R^2') + ggtitle('Adjusted R-Squared')
plot(plot)

#Residual Standard Error
plot <- ggplot() +
  geom_line(data = rollingRegression[Lookback == FALSE], aes(x = Date, y = ResidualStdErr, colour = 'Error')) + 
  xlab('Dates') + ylab('Error') + ggtitle('Standard Error of Residuals')
plot(plot)
```